language: generic 
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t hungngoautonomous/docker-react .
script:
  - docker run hungngoautonomous/docker-react npm run test -- --coverage
deploy:
  provider: heroku
  api_key: 07d023e6-bef1-4280-bc33-239b5aceec14
  app: hungngo-docker-react