language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t hungngoautonomous/docker-react .

scripts:
  - docker run -e CI=true hungngoautonomous/docker-react npm run test -- --coverage